### ISSUE TITLE
Update nodejs script (actions.js) to auto create reducer

### ISSUE THREAD

**Issue by hamzawaleed0102** [hamzawaleed0102/react-native-automated-boilerplate#2]
When user runs command `yarn new appAction getData`, it creates a new action in AppActions.js and actionType in types/index.js.

TODO:

Update this command to append the new states in AppReducer.js

**Comment by NilsKempen** [comment]
I've implemented this with [this](https://github.com/hamzawaleed0102/react-native-automated-boilerplate/pull/5) pr
